sudo: required

language: python
cache: pip
python:
- '2.7'
- '3.5'
- '3.6-dev'

services: docker
install: docker-compose -f test.yml build
script: docker-compose -f test.yml run test /bin/bash -c "curl -s https://codecov.io/env -o cc_env.sh; bash cc_env.sh; python -m pytest --cov=web/ tests; curl -s https://codecov.io/bash -o cc_bash.sh; bash cc_bash.sh -t 52f3918e-1d4a-4f3b-90f4-b18b035582ae"